export const ActionTypes = {
    SET_CONTENTS : "SET_CONTENTS",
    SELECTED_CONTENT: "SELECTED_CONTENT",
    REMOVE_SELECTED_CONTENT : "REMOVE_SELECTED_CONTENT",
    SELECTED_CATEGORY : "SELECTED_CATEGORY"
};

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";